local Cfg_Checkin = {
    [1] = {
        [1] = { Checkin_ID = 1, Checkin_Month = 1, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
        [2] = { Checkin_ID = 1, Checkin_Month = 2, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 1, Checkin_Month = 3, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 1, Checkin_Month = 4, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 1, Checkin_Month = 5, nGoodsID = 100001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 1, Checkin_Month = 6, nGoodsID = 100001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 1, Checkin_Month = 7, nGoodsID = 100001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 1, Checkin_Month = 8, nGoodsID = 100001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 1, Checkin_Month = 9, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 1, Checkin_Month = 10, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 1, Checkin_Month = 11, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 1, Checkin_Month = 12, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
    },
    [2] = {
        [1] = { Checkin_ID = 2, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 2, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 2, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 2, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 2, Checkin_Month = 5, nGoodsID = 100002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 2, Checkin_Month = 6, nGoodsID = 100002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 2, Checkin_Month = 7, nGoodsID = 100002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 2, Checkin_Month = 8, nGoodsID = 100002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 2, Checkin_Month = 9, nGoodsID = 231501, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 2, Checkin_Month = 10, nGoodsID = 231501, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 2, Checkin_Month = 11, nGoodsID = 201027, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 2, Checkin_Month = 12, nGoodsID = 50023, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
    },
    [3] = {
        [1] = { Checkin_ID = 3, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 3, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 3, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 3, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 3, Checkin_Month = 5, nGoodsID = 100003, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 3, Checkin_Month = 6, nGoodsID = 100003, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 3, Checkin_Month = 7, nGoodsID = 100003, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 3, Checkin_Month = 8, nGoodsID = 100003, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 3, Checkin_Month = 9, nGoodsID = 50028, nGoodsNum = 10, nShowNum = 10, nVipDoubleNeed = 1, },
        [10] = { Checkin_ID = 3, Checkin_Month = 10, nGoodsID = 50028, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 1, },
        [11] = { Checkin_ID = 3, Checkin_Month = 11, nGoodsID = 50024, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 1, },
        [12] = { Checkin_ID = 3, Checkin_Month = 12, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
    },
    [4] = {
        [1] = { Checkin_ID = 4, Checkin_Month = 1, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 4, Checkin_Month = 2, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 4, Checkin_Month = 3, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 4, Checkin_Month = 4, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 4, Checkin_Month = 5, nGoodsID = 100004, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 4, Checkin_Month = 6, nGoodsID = 100004, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 4, Checkin_Month = 7, nGoodsID = 100004, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 4, Checkin_Month = 8, nGoodsID = 100004, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 4, Checkin_Month = 9, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 4, Checkin_Month = 10, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 4, Checkin_Month = 11, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 4, Checkin_Month = 12, nGoodsID = 150023, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
    },
    [5] = {
        [1] = { Checkin_ID = 5, Checkin_Month = 1, nGoodsID = 50003, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 5, Checkin_Month = 2, nGoodsID = 50035, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 5, Checkin_Month = 3, nGoodsID = 50023, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 5, Checkin_Month = 4, nGoodsID = 50033, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 5, Checkin_Month = 5, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 5, Checkin_Month = 6, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 5, Checkin_Month = 7, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 5, Checkin_Month = 8, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 5, Checkin_Month = 9, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 2, },
        [10] = { Checkin_ID = 5, Checkin_Month = 10, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 2, },
        [11] = { Checkin_ID = 5, Checkin_Month = 11, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 2, },
        [12] = { Checkin_ID = 5, Checkin_Month = 12, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 2, },
    },
    [6] = {
        [1] = { Checkin_ID = 6, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 6, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 6, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 6, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 6, Checkin_Month = 5, nGoodsID = 100005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 6, Checkin_Month = 6, nGoodsID = 100005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 6, Checkin_Month = 7, nGoodsID = 100005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 6, Checkin_Month = 8, nGoodsID = 100005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 6, Checkin_Month = 9, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 6, Checkin_Month = 10, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 6, Checkin_Month = 11, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 6, Checkin_Month = 12, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
    },
    [7] = {
        [1] = { Checkin_ID = 7, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 7, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 7, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 7, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 7, Checkin_Month = 5, nGoodsID = 201001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 7, Checkin_Month = 6, nGoodsID = 201001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 7, Checkin_Month = 7, nGoodsID = 201001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 7, Checkin_Month = 8, nGoodsID = 201001, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 7, Checkin_Month = 9, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 2, },
        [10] = { Checkin_ID = 7, Checkin_Month = 10, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 2, },
        [11] = { Checkin_ID = 7, Checkin_Month = 11, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 2, },
        [12] = { Checkin_ID = 7, Checkin_Month = 12, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 2, },
    },
    [8] = {
        [1] = { Checkin_ID = 8, Checkin_Month = 1, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
        [2] = { Checkin_ID = 8, Checkin_Month = 2, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 8, Checkin_Month = 3, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 8, Checkin_Month = 4, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 8, Checkin_Month = 5, nGoodsID = 201002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 8, Checkin_Month = 6, nGoodsID = 201002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 8, Checkin_Month = 7, nGoodsID = 201002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 8, Checkin_Month = 8, nGoodsID = 201002, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 8, Checkin_Month = 9, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 3, },
        [10] = { Checkin_ID = 8, Checkin_Month = 10, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 3, },
        [11] = { Checkin_ID = 8, Checkin_Month = 11, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 3, },
        [12] = { Checkin_ID = 8, Checkin_Month = 12, nGoodsID = 121, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
    },
    [9] = {
        [1] = { Checkin_ID = 9, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 9, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 9, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 9, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 9, Checkin_Month = 5, nGoodsID = 201005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 9, Checkin_Month = 6, nGoodsID = 201005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 9, Checkin_Month = 7, nGoodsID = 201005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 9, Checkin_Month = 8, nGoodsID = 201005, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 9, Checkin_Month = 9, nGoodsID = 201027, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 9, Checkin_Month = 10, nGoodsID = 201044, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 9, Checkin_Month = 11, nGoodsID = 201048, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 9, Checkin_Month = 12, nGoodsID = 50023, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
    },
    [10] = {
        [1] = { Checkin_ID = 10, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 5, nShowNum = 5, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 10, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 5, nShowNum = 5, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 10, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 5, nShowNum = 5, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 10, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 10, Checkin_Month = 5, nGoodsID = 201006, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 10, Checkin_Month = 6, nGoodsID = 201006, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 10, Checkin_Month = 7, nGoodsID = 201006, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 10, Checkin_Month = 8, nGoodsID = 201006, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 10, Checkin_Month = 9, nGoodsID = 50028, nGoodsNum = 15, nShowNum = 15, nVipDoubleNeed = 3, },
        [10] = { Checkin_ID = 10, Checkin_Month = 10, nGoodsID = 50028, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = 3, },
        [11] = { Checkin_ID = 10, Checkin_Month = 11, nGoodsID = 50024, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = 3, },
        [12] = { Checkin_ID = 10, Checkin_Month = 12, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
    },
    [11] = {
        [1] = { Checkin_ID = 11, Checkin_Month = 1, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 11, Checkin_Month = 2, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 11, Checkin_Month = 3, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 11, Checkin_Month = 4, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 11, Checkin_Month = 5, nGoodsID = 201009, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 11, Checkin_Month = 6, nGoodsID = 201009, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 11, Checkin_Month = 7, nGoodsID = 201009, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 11, Checkin_Month = 8, nGoodsID = 201009, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 11, Checkin_Month = 9, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 11, Checkin_Month = 10, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 11, Checkin_Month = 11, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 11, Checkin_Month = 12, nGoodsID = 150023, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
    },
    [12] = {
        [1] = { Checkin_ID = 12, Checkin_Month = 1, nGoodsID = 50003, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 12, Checkin_Month = 2, nGoodsID = 50035, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 12, Checkin_Month = 3, nGoodsID = 50023, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 12, Checkin_Month = 4, nGoodsID = 50033, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 12, Checkin_Month = 5, nGoodsID = 201010, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 12, Checkin_Month = 6, nGoodsID = 201010, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 12, Checkin_Month = 7, nGoodsID = 201010, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 12, Checkin_Month = 8, nGoodsID = 201010, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 12, Checkin_Month = 9, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 4, },
        [10] = { Checkin_ID = 12, Checkin_Month = 10, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 4, },
        [11] = { Checkin_ID = 12, Checkin_Month = 11, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 4, },
        [12] = { Checkin_ID = 12, Checkin_Month = 12, nGoodsID = 100005, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 2, },
    },
    [13] = {
        [1] = { Checkin_ID = 13, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 13, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 13, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 13, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 13, Checkin_Month = 5, nGoodsID = 201013, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 13, Checkin_Month = 6, nGoodsID = 201013, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 13, Checkin_Month = 7, nGoodsID = 201013, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 13, Checkin_Month = 8, nGoodsID = 201013, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 13, Checkin_Month = 9, nGoodsID = 2, nGoodsNum = 75, nShowNum = 75, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 13, Checkin_Month = 10, nGoodsID = 2, nGoodsNum = 75, nShowNum = 75, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 13, Checkin_Month = 11, nGoodsID = 2, nGoodsNum = 75, nShowNum = 75, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 13, Checkin_Month = 12, nGoodsID = 2, nGoodsNum = 75, nShowNum = 75, nVipDoubleNeed = -1, },
    },
    [14] = {
        [1] = { Checkin_ID = 14, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 14, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 14, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 14, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 5, nShowNum = 5, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 14, Checkin_Month = 5, nGoodsID = 201014, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 14, Checkin_Month = 6, nGoodsID = 201014, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 14, Checkin_Month = 7, nGoodsID = 201014, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 14, Checkin_Month = 8, nGoodsID = 201014, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 14, Checkin_Month = 9, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 4, },
        [10] = { Checkin_ID = 14, Checkin_Month = 10, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 4, },
        [11] = { Checkin_ID = 14, Checkin_Month = 11, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 4, },
        [12] = { Checkin_ID = 14, Checkin_Month = 12, nGoodsID = 103, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = 2, },
    },
    [15] = {
        [1] = { Checkin_ID = 15, Checkin_Month = 1, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 1, },
        [2] = { Checkin_ID = 15, Checkin_Month = 2, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 15, Checkin_Month = 3, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 15, Checkin_Month = 4, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 15, Checkin_Month = 5, nGoodsID = 201017, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 15, Checkin_Month = 6, nGoodsID = 201017, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 15, Checkin_Month = 7, nGoodsID = 201017, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 15, Checkin_Month = 8, nGoodsID = 201017, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 15, Checkin_Month = 9, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 5, },
        [10] = { Checkin_ID = 15, Checkin_Month = 10, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 5, },
        [11] = { Checkin_ID = 15, Checkin_Month = 11, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 5, },
        [12] = { Checkin_ID = 15, Checkin_Month = 12, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
    },
    [16] = {
        [1] = { Checkin_ID = 16, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 16, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 16, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 16, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 16, Checkin_Month = 5, nGoodsID = 201018, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 16, Checkin_Month = 6, nGoodsID = 201018, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 16, Checkin_Month = 7, nGoodsID = 201018, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 16, Checkin_Month = 8, nGoodsID = 201018, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 16, Checkin_Month = 9, nGoodsID = 201051, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 16, Checkin_Month = 10, nGoodsID = 201032, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 16, Checkin_Month = 11, nGoodsID = 201051, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 16, Checkin_Month = 12, nGoodsID = 50023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
    },
    [17] = {
        [1] = { Checkin_ID = 17, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 7, nShowNum = 7, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 17, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 7, nShowNum = 7, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 17, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 7, nShowNum = 7, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 17, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 7, nShowNum = 7, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 17, Checkin_Month = 5, nGoodsID = 201019, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 17, Checkin_Month = 6, nGoodsID = 201019, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 17, Checkin_Month = 7, nGoodsID = 201019, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 17, Checkin_Month = 8, nGoodsID = 201019, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 17, Checkin_Month = 9, nGoodsID = 50028, nGoodsNum = 20, nShowNum = 20, nVipDoubleNeed = 5, },
        [10] = { Checkin_ID = 17, Checkin_Month = 10, nGoodsID = 50028, nGoodsNum = 10, nShowNum = 10, nVipDoubleNeed = 5, },
        [11] = { Checkin_ID = 17, Checkin_Month = 11, nGoodsID = 50024, nGoodsNum = 10, nShowNum = 10, nVipDoubleNeed = 5, },
        [12] = { Checkin_ID = 17, Checkin_Month = 12, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
    },
    [18] = {
        [1] = { Checkin_ID = 18, Checkin_Month = 1, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 18, Checkin_Month = 2, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 18, Checkin_Month = 3, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 18, Checkin_Month = 4, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 18, Checkin_Month = 5, nGoodsID = 201020, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 18, Checkin_Month = 6, nGoodsID = 201020, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 18, Checkin_Month = 7, nGoodsID = 201020, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 18, Checkin_Month = 8, nGoodsID = 201020, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 18, Checkin_Month = 9, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 18, Checkin_Month = 10, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 18, Checkin_Month = 11, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 18, Checkin_Month = 12, nGoodsID = 150023, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
    },
    [19] = {
        [1] = { Checkin_ID = 19, Checkin_Month = 1, nGoodsID = 50003, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 19, Checkin_Month = 2, nGoodsID = 50035, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 19, Checkin_Month = 3, nGoodsID = 50023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 19, Checkin_Month = 4, nGoodsID = 50033, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 19, Checkin_Month = 5, nGoodsID = 201021, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 19, Checkin_Month = 6, nGoodsID = 201021, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 19, Checkin_Month = 7, nGoodsID = 201021, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 19, Checkin_Month = 8, nGoodsID = 201021, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 19, Checkin_Month = 9, nGoodsID = 100005, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 6, },
        [10] = { Checkin_ID = 19, Checkin_Month = 10, nGoodsID = 100005, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 6, },
        [11] = { Checkin_ID = 19, Checkin_Month = 11, nGoodsID = 100005, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = 6, },
        [12] = { Checkin_ID = 19, Checkin_Month = 12, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 2, },
    },
    [20] = {
        [1] = { Checkin_ID = 20, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 20, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 20, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 20, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 20, Checkin_Month = 5, nGoodsID = 201022, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 20, Checkin_Month = 6, nGoodsID = 201022, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 20, Checkin_Month = 7, nGoodsID = 201022, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 20, Checkin_Month = 8, nGoodsID = 201022, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 20, Checkin_Month = 9, nGoodsID = 2, nGoodsNum = 100, nShowNum = 100, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 20, Checkin_Month = 10, nGoodsID = 2, nGoodsNum = 100, nShowNum = 100, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 20, Checkin_Month = 11, nGoodsID = 2, nGoodsNum = 100, nShowNum = 100, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 20, Checkin_Month = 12, nGoodsID = 2, nGoodsNum = 100, nShowNum = 100, nVipDoubleNeed = -1, },
    },
    [21] = {
        [1] = { Checkin_ID = 21, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 21, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 21, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 21, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 21, Checkin_Month = 5, nGoodsID = 201023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 21, Checkin_Month = 6, nGoodsID = 201023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 21, Checkin_Month = 7, nGoodsID = 201023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 21, Checkin_Month = 8, nGoodsID = 201023, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 21, Checkin_Month = 9, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = 6, },
        [10] = { Checkin_ID = 21, Checkin_Month = 10, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = 6, },
        [11] = { Checkin_ID = 21, Checkin_Month = 11, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = 6, },
        [12] = { Checkin_ID = 21, Checkin_Month = 12, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = 2, },
    },
    [22] = {
        [1] = { Checkin_ID = 22, Checkin_Month = 1, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 1, },
        [2] = { Checkin_ID = 22, Checkin_Month = 2, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 22, Checkin_Month = 3, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 22, Checkin_Month = 4, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 22, Checkin_Month = 5, nGoodsID = 201024, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 22, Checkin_Month = 6, nGoodsID = 201024, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 22, Checkin_Month = 7, nGoodsID = 201024, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 22, Checkin_Month = 8, nGoodsID = 201024, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 22, Checkin_Month = 9, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 7, },
        [10] = { Checkin_ID = 22, Checkin_Month = 10, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 7, },
        [11] = { Checkin_ID = 22, Checkin_Month = 11, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 7, },
        [12] = { Checkin_ID = 22, Checkin_Month = 12, nGoodsID = 121, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
    },
    [23] = {
        [1] = { Checkin_ID = 23, Checkin_Month = 1, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = 2, },
        [2] = { Checkin_ID = 23, Checkin_Month = 2, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 23, Checkin_Month = 3, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 23, Checkin_Month = 4, nGoodsID = 2, nGoodsNum = 50, nShowNum = 50, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 23, Checkin_Month = 5, nGoodsID = 201025, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 23, Checkin_Month = 6, nGoodsID = 201025, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 23, Checkin_Month = 7, nGoodsID = 201025, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 23, Checkin_Month = 8, nGoodsID = 201025, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 23, Checkin_Month = 9, nGoodsID = 201039, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 23, Checkin_Month = 10, nGoodsID = 201048, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 23, Checkin_Month = 11, nGoodsID = 201039, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 23, Checkin_Month = 12, nGoodsID = 50023, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
    },
    [24] = {
        [1] = { Checkin_ID = 24, Checkin_Month = 1, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 24, Checkin_Month = 2, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 24, Checkin_Month = 3, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 24, Checkin_Month = 4, nGoodsID = 103, nGoodsNum = 9, nShowNum = 9, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 24, Checkin_Month = 5, nGoodsID = 201026, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 24, Checkin_Month = 6, nGoodsID = 201026, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 24, Checkin_Month = 7, nGoodsID = 201026, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 24, Checkin_Month = 8, nGoodsID = 201026, nGoodsNum = 6, nShowNum = 6, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 24, Checkin_Month = 9, nGoodsID = 50028, nGoodsNum = 25, nShowNum = 25, nVipDoubleNeed = 7, },
        [10] = { Checkin_ID = 24, Checkin_Month = 10, nGoodsID = 50028, nGoodsNum = 12, nShowNum = 12, nVipDoubleNeed = 7, },
        [11] = { Checkin_ID = 24, Checkin_Month = 11, nGoodsID = 50024, nGoodsNum = 12, nShowNum = 12, nVipDoubleNeed = 7, },
        [12] = { Checkin_ID = 24, Checkin_Month = 12, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = 1, },
    },
    [25] = {
        [1] = { Checkin_ID = 25, Checkin_Month = 1, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 25, Checkin_Month = 2, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 25, Checkin_Month = 3, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 25, Checkin_Month = 4, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 25, Checkin_Month = 5, nGoodsID = 201027, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 25, Checkin_Month = 6, nGoodsID = 201027, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 25, Checkin_Month = 7, nGoodsID = 201027, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 25, Checkin_Month = 8, nGoodsID = 201027, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 25, Checkin_Month = 9, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [10] = { Checkin_ID = 25, Checkin_Month = 10, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [11] = { Checkin_ID = 25, Checkin_Month = 11, nGoodsID = 10, nGoodsNum = 1, nShowNum = 1, nVipDoubleNeed = -1, },
        [12] = { Checkin_ID = 25, Checkin_Month = 12, nGoodsID = 150023, nGoodsNum = 3, nShowNum = 3, nVipDoubleNeed = -1, },
    },
    [26] = {
        [1] = { Checkin_ID = 26, Checkin_Month = 1, nGoodsID = 50003, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [2] = { Checkin_ID = 26, Checkin_Month = 2, nGoodsID = 50035, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [3] = { Checkin_ID = 26, Checkin_Month = 3, nGoodsID = 50023, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [4] = { Checkin_ID = 26, Checkin_Month = 4, nGoodsID = 50033, nGoodsNum = 8, nShowNum = 8, nVipDoubleNeed = -1, },
        [5] = { Checkin_ID = 26, Checkin_Month = 5, nGoodsID = 201028, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [6] = { Checkin_ID = 26, Checkin_Month = 6, nGoodsID = 201028, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [7] = { Checkin_ID = 26, Checkin_Month = 7, nGoodsID = 201028, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [8] = { Checkin_ID = 26, Checkin_Month = 8, nGoodsID = 201028, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = -1, },
        [9] = { Checkin_ID = 26, Checkin_Month = 9, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = 8, },
        [10] = { Checkin_ID = 26, Checkin_Month = 10, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = 8, },
        [11] = { Checkin_ID = 26, Checkin_Month = 11, nGoodsID = 100005, nGoodsNum = 4, nShowNum = 4, nVipDoubleNeed = 8, },
        [12] = { Checkin_ID = 26, Checkin_Month = 12, nGoodsID = 100005, nGoodsNum = 2, nShowNum = 2, nVipDoubleNeed = 2, },
    },
}
return Cfg_Checkin