local Cfg_FunNameToID = {
    [1] = { KEY = "Is_None", VAL = 1, },
    [2] = { KEY = "Is_FindTarget", VAL = 2, },
    [3] = { KEY = "Is_HasTarget", VAL = 3, },
    [4] = { KEY = "Is_MyHpLessThan", VAL = 4, },
    [5] = { KEY = "Is_SkillReady", VAL = 5, },
    [6] = { KEY = "Is_HasTargetPoint", VAL = 6, },
    [7] = { KEY = "Is_MyBuff", VAL = 7, },
    [8] = { KEY = "Is_RedOrBlue", VAL = 8, },
    [9] = { KEY = "Is_RandomForAI", VAL = 9, },
    [10] = { KEY = "Is_MyStarForAI", VAL = 10, },
    [11] = { KEY = "Is_MyAttribute", VAL = 11, },
    [12] = { KEY = "Is_MySkillLevelForAI", VAL = 12, },
    [13] = { KEY = "", VAL = 0, },
    [14] = { KEY = "Do_None", VAL = 1, },
    [15] = { KEY = "Do_LockMe", VAL = 2, },
    [16] = { KEY = "Do_Clear", VAL = 3, },
    [17] = { KEY = "Do_ChangeStatus", VAL = 4, },
    [18] = { KEY = "Do_CastSkill", VAL = 5, },
    [19] = { KEY = "Do_LockPoints", VAL = 6, },
    [20] = { KEY = "Do_LockPointsForMe", VAL = 7, },
    [21] = { KEY = "Do_AddBuffForMe", VAL = 8, },
    [22] = { KEY = "Do_DelBuffForMe", VAL = 9, },
    [23] = { KEY = "Do_Count", VAL = 10, },
    [24] = { KEY = "Do_LuaEvent", VAL = 11, },
    [25] = { KEY = "", VAL = 0, },
    [26] = { KEY = "None", VAL = 0, },
    [27] = { KEY = "Move", VAL = 1, },
    [28] = { KEY = "HitPower", VAL = 2, },
    [29] = { KEY = "Dead", VAL = 3, },
    [30] = { KEY = "", VAL = 0, },
    [31] = { KEY = "Is_HasBuffTarget", VAL = 1, },
    [32] = { KEY = "Is_HasSkillPoint", VAL = 2, },
    [33] = { KEY = "Is_BuffSkillReady", VAL = 3, },
    [34] = { KEY = "Is_Random", VAL = 4, },
}
return Cfg_FunNameToID