local Cfg_GuildLan = {
    [1] = { ID = 1, Content = "<br/><font face='fonts/msyh.ttf' size='22'><font face='fonts/msyh.ttf' color='B3EE3A' size='24'>敌人</font>位于关卡右边！</font>", },
    [2] = { ID = 2, Content = "<br/><font face='fonts/msyh.ttf' size='22'>在游戏中，你将扮演<font face='fonts/msyh.ttf' color='B3EE3A' size='24'>召唤师</font>！击败对面的敌人以取得胜利！</font>", },
    [3] = { ID = 3, Content = "点击释放召唤师技能", },
    [4] = { ID = 4, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>水晶</font>，是召唤师力量的源泉，消耗一定量的水晶可将水晶等级提升，并解锁<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>召唤师技能</font>！点击<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>水晶按钮</font>升级水晶！</font>", },
    [5] = { ID = 5, Content = "<font face='fonts/msyh.ttf' size='20'>点击<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>英雄头像</font>即可召唤他们出战，召唤英雄需要消耗水晶，每个英雄都有自己的<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>水晶消耗值</font>！</font>", },
    [6] = { ID = 6, Content = "<font face='fonts/msyh.ttf' size='21'>己方英雄会在召唤师身后出现，每个英雄都有各自的<font face='fonts/msyh.ttf' color='B3EE3A' size='22'>冷却时间</font>，根据战场形势召唤合适的英雄是制胜的关键！</font>", },
    [7] = { ID = 7, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>埃迪</font>：我身手矫捷，擅长对付高血量的敌人</font>", },
    [8] = { ID = 8, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>火枪手</font>：只要有战士的掩护，我就能在后排输出成吨的伤害</font>", },
    [9] = { ID = 9, Content = "召唤师，今天就是你的死期！", },
    [10] = { ID = 10, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>技能：冲锋号角</font>，可以提升己方英雄的<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>攻速</font>和<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>移速</font>！</font>", },
    [11] = { ID = 11, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='22'>觉醒</font>：终极技能，可以对敌人造成重创！</font>", },
    [12] = { ID = 12, Content = "点击水晶按钮升级水晶", },
    [13] = { ID = 13, Content = "<font face='fonts/msyh.ttf' size='22'>召唤师技能会在水晶达到<font face='fonts/msyh.ttf' color='B3EE3A' size='24'>2-3-4</font>这三个等级时，依次解锁！</font>", },
    [14] = { ID = 14, Content = "<font face='fonts/msyh.ttf' size='21'>当场上敌方的英雄较多时，可以使用召唤师技能缓解一下局势，技能CD已经完成了，尝试着释放一次吧！</font>", },
    [15] = { ID = 15, Content = "点击释放召唤师终极技能", },
    [16] = { ID = 16, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>技能：剑气斩</font>，可以对敌人造成多段伤害！</font>", },
    [17] = { ID = 17, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>盗贼</font>：我是一个刺客，可以绕过前排切入后排！</font>", },
    [18] = { ID = 18, Content = "呼~~累死我了，这种天气还让我来这里，妮莎你是有什么急事吗？", },
    [19] = { ID = 19, Content = "之前你说要参加竞技场的比赛，今天是要教你一些战斗技巧，我还特地拜托了艾丽卡来和你进行练习！", },
    [20] = { ID = 20, Content = "<font face='fonts/msyh.ttf' size='20'>你的身份是一名<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>召唤师</font>，你战斗的位置在地图<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>左侧</font>，而你的对手在地图<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>右侧</font>。</font>", },
    [21] = { ID = 21, Content = "<font face='fonts/msyh.ttf' size='20'>现在<font face='fonts/msyh.ttf' color='B3EE3A' size='22'>艾丽卡</font>就是你的对手，击败你的对手，即可获得胜利！</font>", },
    [22] = { ID = 22, Content = "原来是个萌妹子，看起来没什么战斗力啊~没意思！", },
    [23] = { ID = 23, Content = "哼！要不是妮莎拜托我，我才懒得和你这个竞技场菜鸟对战！", },
    [24] = { ID = 24, Content = "哈哈哈~要是输了你可别哭鼻子哟！", },
    [25] = { ID = 25, Content = "来啊，互相伤害啊！谁怕谁啊！", },
    [27] = { ID = 27, Content = "点击英雄头像召唤林克！", },
    [28] = { ID = 28, Content = "噢~正好可以当做热身，那我们快点开始吧！", },
    [29] = { ID = 29, Content = "点击英雄头像召唤火枪手！", },
    [30] = { ID = 30, Content = "点击英雄头像召唤盗贼！", },
    [31] = { ID = 31, Content = "<font face='fonts/msyh.ttf' size='20'>在面对大批敌人时，剑气斩击可以很好地减缓场面上的压力！点击<font face='fonts/msyh.ttf' color='B3EE3A' size='21'>技能图标</font>释放技能！</font>", },
    [32] = { ID = 32, Content = "哇！技能这么叼啊？那我水晶直接升到4级岂不是更叼？", },
    [33] = { ID = 33, Content = "升到4级是很厉害，但是你升级是会消耗大量水晶的，这个期间你是没有水晶召唤英雄的，所以要合理的搭配发兵和升级时间！继续召唤英雄击败敌人吧！", },
    [34] = { ID = 34, Content = "哎哎哎？怎么她一上来就能召唤野兽？", },
    [35] = { ID = 35, Content = "别慌，你也是召唤师！我来教你如何召唤自己的英雄！", },
    [36] = { ID = 36, Content = "原来艾丽卡的能力是能够治疗受伤的同伴啊，为什么我不能使用自己的能力呢？", },
    [37] = { ID = 37, Content = "你的战场洞察力不错，召唤师们都有自己特有的能力，我来教你如何解锁召唤师技能！", },
    [38] = { ID = 38, Content = "实战的感觉果然不一样，想不到还有这么多细节要注意，热身完毕，接下来就要在竞技场大显身手了！", },
    [39] = { ID = 39, Content = "继续努力吧，你要学的东西还很多！", },
    [40] = { ID = 40, Content = "可恶！有基佬拉我裤链！", },
    [41] = { ID = 41, Content = "火枪手：只要有战士的掩护，我就能在后排输出成吨的伤害！", },
    [42] = { ID = 42, Content = "盗贼：我擅长利用潜行避开战士，从而奇袭后排的敌人！", },
    [43] = { ID = 43, Content = "点击英雄头像继续召唤英雄！", },
    [44] = { ID = 44, Content = "欢迎来到竞技场，刚才你已经学习了一些基本的战斗技巧，现在去再熟悉一下你学的东西吧！", },
    [45] = { ID = 45, Content = "点击匹配按钮开始战斗", },
    [102] = { ID = 102, Content = "一键编队可以快速配置队伍，你也可以自由进行队伍配置。", },
    [103] = { ID = 103, Content = "村子里有一位很漂亮的妹妹送了你一张抽卡券，快去看看吧！", },
    [104] = { ID = 104, Content = "日常任务开启了，记得经常查看任务，随时会有新的任务开启哦！", },
    [113] = { ID = 113, Content = "莱奥哥哥，你看埃迪的实力提升了好多！", },
    [114] = { ID = 114, Content = "        竞技场可是高手云集的地方，想要大显身手的话就多来这里和其他玩家进行对战吧！", },
    [116] = { ID = 116, Content = "抽卡券可以随机获得一名英雄，快去召唤大厅试试手气吧！", },
    [117] = { ID = 117, Content = "      点击按钮抽卡", },
    [118] = { ID = 118, Content = "偷偷告诉你一个小技巧：三星通关后使用扫荡功能可以快速获取关卡掉落哦！", },
    [121] = { ID = 121, Content = "在这里你可以查看英雄的信息，还可以管理他们的各种能力~我们先来学习下给英雄升级吧！", },
    [124] = { ID = 124, Content = "通过升级可以提升英雄能力", },
    [125] = { ID = 125, Content = "使用你的升级道具", },
    [126] = { ID = 126, Content = "食物可以让英雄获得升级所需的经验，越高级的食物提供的经验越多！", },
    [127] = { ID = 127, Content = "英雄升级之后能获得基础属性成长！", },
    [128] = { ID = 128, Content = "召唤师系统已经开始，快点去看看新的召唤师吧！", },
    [134] = { ID = 134, Content = "金币试炼已开启！完成挑战的同时可以获得大量金币奖励哦！", },
    [147] = { ID = 147, Content = "这里可以详细的查看所有召唤师的技能介绍和角色信息。", },
    [148] = { ID = 148, Content = "精英关卡可以获取英雄提升的材料！不过要确保自己实力足够再进行挑战哦！", },
    [149] = { ID = 149, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>小鹿</font>：我是来自森林的法师，可以帮你消灭大量的敌人！</font>", },
    [150] = { ID = 150, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>盾卫</font>：我是盾卫，请到我身后~我会用盾牌保护你们的！</font>", },
    [151] = { ID = 151, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>牧师</font>：我可以帮友军提供治疗！</font>", },
    [152] = { ID = 152, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>盗贼</font>：我擅长利用潜行避开战士，从而奇袭后排的敌人！</font>", },
    [234] = { ID = 234, Content = "英雄试炼已开启！在这里可以获得提升英雄等级的经验食物！", },
    [235] = { ID = 235, Content = "爬塔试炼已开启！接受层层挑战可以获得兑换神秘商品的能量碎片！", },
    [236] = { ID = 236, Content = "铁匠铺功能已经开启啦！快去那里打造你心仪的装备吧！", },
    [237] = { ID = 237, Content = "公会系统已经开启啦！快去那里找你的小伙伴吧！", },
    [506] = { ID = 506, Content = "莱奥哥哥，我们刚获得了一套装备，先帮勇士埃迪穿上吧！", },
    [548] = { ID = 548, Content = "选择英雄领悟的天赋", },
    [549] = { ID = 549, Content = "去战斗中体验英雄天赋带来的提升效果吧！", },
    [550] = { ID = 550, Content = "帮你的英雄解锁天赋技能", },
    [627] = { ID = 627, Content = "抽卡", },
    [628] = { ID = 628, Content = "抽卡系统已解锁", },
    [629] = { ID = 629, Content = "任务", },
    [630] = { ID = 630, Content = "任务系统已解锁", },
    [631] = { ID = 631, Content = "背包", },
    [632] = { ID = 632, Content = "背包系统已解锁", },
    [633] = { ID = 633, Content = "英雄", },
    [634] = { ID = 634, Content = "英雄系统已解锁", },
    [635] = { ID = 635, Content = "商店", },
    [636] = { ID = 636, Content = "商店系统已解锁", },
    [637] = { ID = 637, Content = "竞技场", },
    [638] = { ID = 638, Content = "竞技场系统已解锁", },
    [639] = { ID = 639, Content = "召唤师", },
    [640] = { ID = 640, Content = "召唤师系统已解锁", },
    [641] = { ID = 641, Content = "升星", },
    [642] = { ID = 642, Content = "升星和天赋系统已解锁", },
    [643] = { ID = 643, Content = "副本", },
    [644] = { ID = 644, Content = "金币试练已解锁", },
    [645] = { ID = 645, Content = "英雄试炼已解锁", },
    [646] = { ID = 646, Content = "爬塔试炼解锁", },
    [647] = { ID = 647, Content = "第四关通关后解锁", },
    [648] = { ID = 648, Content = "15关通关后解锁", },
    [649] = { ID = 649, Content = "20级解锁副本系统", },
    [650] = { ID = 650, Content = "23级解锁英雄试练", },
    [651] = { ID = 651, Content = "26级解锁英雄试练", },
    [652] = { ID = 652, Content = "第六关通关后解锁", },
    [653] = { ID = 653, Content = "第四关通关后解锁", },
    [654] = { ID = 654, Content = "铁匠铺", },
    [655] = { ID = 655, Content = "装备打造系统已解锁", },
    [656] = { ID = 656, Content = "公会", },
    [657] = { ID = 657, Content = "公会系统已解锁", },
    [658] = { ID = 658, Content = "通关第一章第十五关解锁公会系统", },
    [659] = { ID = 659, Content = "通关第一章第八关解锁召唤师系统", },
    [660] = { ID = 660, Content = "通关第六关解锁英雄系统", },
    [661] = { ID = 661, Content = "通关第六关解锁升星系统", },
    [662] = { ID = 662, Content = "通关第一章第十二关解锁副本试炼系统", },
    [663] = { ID = 663, Content = "通关第二章第九关解锁英雄试炼，可通过试炼获得经验食物", },
    [664] = { ID = 664, Content = "通关第三章第三关解锁爬塔试炼，通过爬塔试炼可获取装备材料", },
    [665] = { ID = 665, Content = "通关第一章第八关解锁竞技场系统", },
    [666] = { ID = 666, Content = "通关第六关解锁背包系统", },
    [667] = { ID = 667, Content = "通关第二章第一关解锁装备打造系统", },
    [668] = { ID = 668, Content = "通关第一章第八关解锁神秘商店", },
    [669] = { ID = 669, Content = "通关第一章第十二关解锁金币试炼", },
    [1001] = { ID = 1001, Content = "森巨人：我受伤了，需要治疗！！", },
    [1505] = { ID = 1505, Content = "莱奥", },
    [1510] = { ID = 1510, Content = "艾丽卡", },
    [1553] = { ID = 1553, Content = "妮莎", },
    [1554] = { ID = 1554, Content = "牧师", },
    [1555] = { ID = 1555, Content = "佩丽丝", },
    [1556] = { ID = 1556, Content = "新手引导员", },
    [100101] = { ID = 100101, Content = "可恶的老头子，总是拿他那条破龙来折磨我！等本大爷收集足够的英雄卡牌之后，我一定……", },
    [100102] = { ID = 100102, Content = "莱奥你在那嘀咕什么呢？今天的训练先到这了，先去山下村长家给我带壶酒来，记住要温的。", },
    [100103] = { ID = 100103, Content = "在面对大批敌人时，剑气斩击可以很好地减缓场面上的压力！", },
    [100104] = { ID = 100104, Content = "是，师傅，我马上下山！", },
    [100105] = { ID = 100105, Content = "如果准备好的话，那我们就开始冒险吧！", },
    [110107] = { ID = 110107, Content = "脆皮火枪手需要在勇士的掩护下进行输出！", },
    [110201] = { ID = 110201, Content = "小鹿的流星雨是狼群的克星，要保护好她哟！", },
    [110202] = { ID = 110202, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>盾卫</font>：请到我身后~我会用盾牌保护你们的！</font>", },
    [110301] = { ID = 110301, Content = "今天的野兽感觉特别活跃呢？", },
    [110302] = { ID = 110302, Content = "黄毛小子！竟敢打伤我的小熊和小狼！受死吧！", },
    [110303] = { ID = 110303, Content = "唉！等等...你听我解释...", },
    [110304] = { ID = 110304, Content = "说起来你可能不信，是它们先动手的......", },
    [110305] = { ID = 110305, Content = "哼！看招！", },
    [110306] = { ID = 110306, Content = "咦？这丢过来的是什么东西？", },
    [110307] = { ID = 110307, Content = "莱奥哥哥，这可是抽卡券哦~快来城镇找我吧！", },
    [110401] = { ID = 110401, Content = "牧师拥有极强的治疗能力，是必不可少的后勤保证！", },
    [110402] = { ID = 110402, Content = "我们已经有了新的英雄牧师，现在把牧师也加入队伍吧！", },
    [110403] = { ID = 110403, Content = "<font face='fonts/msyh.ttf' size='20'><font face='fonts/msyh.ttf' color='B3EE3A' size='21'>牧师</font>：治疗和回复的工作就交给我吧！</font>", },
    [110404] = { ID = 110404, Content = "村长，师傅让我打酒来了！", },
    [110405] = { ID = 110405, Content = "还打什么酒！没看到后面两个巨人都打起来了吗？", },
    [110406] = { ID = 110406, Content = "你小子还挺有两下子的嘛~我这里还有点下酒菜，你也一起拿走吧！", },
    [110407] = { ID = 110407, Content = "谢谢村长了，村长您当年不是有套勇士装嘛~反正你也用不上了，索性给我呗！", },
    [110408] = { ID = 110408, Content = "你小子还真是…", },
    [110501] = { ID = 110501, Content = "盗贼潜行后可以绕开敌方战士偷袭后排！", },
    [110502] = { ID = 110502, Content = "黄毛小子！你竟然偷走了我的抽卡券！快还我！", },
    [110503] = { ID = 110503, Content = "讲道理，明明就是你丢过来的好吗！", },
    [110504] = { ID = 110504, Content = "哼！我们走着瞧！", },
}
return Cfg_GuildLan