local Cfg_Push = {
    [1] = { Push_ID = 1, Push_On = 1, Push_StartTime = 1, Push_StopTime = -1, Push_Time = 12, Push_Condition = 1, Push_Next = {[1]=1,}, Push_LanID = 101, Push_Range = 1, },
    [2] = { Push_ID = 2, Push_On = 1, Push_StartTime = 1, Push_StopTime = -1, Push_Time = 20, Push_Condition = 2, Push_Next = {[1]=2,}, Push_LanID = 102, Push_Range = 1, },
    [3] = { Push_ID = 3, Push_On = 1, Push_StartTime = 2, Push_StopTime = 3, Push_Time = 11, Push_Condition = 3, Push_Next = {}, Push_LanID = 103, Push_Range = 0, },
    [4] = { Push_ID = 4, Push_On = 1, Push_StartTime = 2, Push_StopTime = 3, Push_Time = 16, Push_Condition = 3, Push_Next = {}, Push_LanID = 104, Push_Range = 0, },
    [5] = { Push_ID = 5, Push_On = 1, Push_StartTime = 2, Push_StopTime = 3, Push_Time = 21, Push_Condition = 3, Push_Next = {}, Push_LanID = 105, Push_Range = 0, },
    [6] = { Push_ID = 6, Push_On = 1, Push_StartTime = 3, Push_StopTime = 4, Push_Time = 10, Push_Condition = 3, Push_Next = {}, Push_LanID = 106, Push_Range = 0, },
    [7] = { Push_ID = 7, Push_On = 1, Push_StartTime = 3, Push_StopTime = 4, Push_Time = 17, Push_Condition = 3, Push_Next = {}, Push_LanID = 107, Push_Range = 0, },
    [8] = { Push_ID = 8, Push_On = 1, Push_StartTime = 4, Push_StopTime = 5, Push_Time = 10, Push_Condition = 3, Push_Next = {}, Push_LanID = 108, Push_Range = 0, },
    [9] = { Push_ID = 9, Push_On = 1, Push_StartTime = 4, Push_StopTime = 5, Push_Time = 17, Push_Condition = 3, Push_Next = {}, Push_LanID = 109, Push_Range = 0, },
    [10] = { Push_ID = 10, Push_On = 1, Push_StartTime = 5, Push_StopTime = 6, Push_Time = 10, Push_Condition = 3, Push_Next = {}, Push_LanID = 110, Push_Range = 0, },
    [11] = { Push_ID = 11, Push_On = 1, Push_StartTime = 5, Push_StopTime = 6, Push_Time = 17, Push_Condition = 3, Push_Next = {}, Push_LanID = 111, Push_Range = 0, },
    [12] = { Push_ID = 12, Push_On = 1, Push_StartTime = 6, Push_StopTime = 7, Push_Time = 10, Push_Condition = 3, Push_Next = {}, Push_LanID = 112, Push_Range = 0, },
    [13] = { Push_ID = 13, Push_On = 1, Push_StartTime = 6, Push_StopTime = 7, Push_Time = 17, Push_Condition = 3, Push_Next = {}, Push_LanID = 113, Push_Range = 0, },
    [14] = { Push_ID = 14, Push_On = 1, Push_StartTime = 7, Push_StopTime = 8, Push_Time = 10, Push_Condition = 3, Push_Next = {}, Push_LanID = 114, Push_Range = 0, },
    [15] = { Push_ID = 15, Push_On = 1, Push_StartTime = 7, Push_StopTime = 8, Push_Time = 17, Push_Condition = 3, Push_Next = {}, Push_LanID = 115, Push_Range = 0, },
    [16] = { Push_ID = 16, Push_On = 1, Push_StartTime = 3, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=18,}, Push_LanID = 116, Push_Range = 7, },
    [17] = { Push_ID = 17, Push_On = 1, Push_StartTime = 3, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=19,}, Push_LanID = 117, Push_Range = 7, },
    [18] = { Push_ID = 18, Push_On = 0, Push_StartTime = 4, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=20,}, Push_LanID = 118, Push_Range = 7, },
    [19] = { Push_ID = 19, Push_On = 0, Push_StartTime = 4, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=21,}, Push_LanID = 119, Push_Range = 7, },
    [20] = { Push_ID = 20, Push_On = 0, Push_StartTime = 5, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=22,}, Push_LanID = 120, Push_Range = 7, },
    [21] = { Push_ID = 21, Push_On = 0, Push_StartTime = 5, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=23,}, Push_LanID = 121, Push_Range = 7, },
    [22] = { Push_ID = 22, Push_On = 0, Push_StartTime = 6, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=24,}, Push_LanID = 122, Push_Range = 7, },
    [23] = { Push_ID = 23, Push_On = 0, Push_StartTime = 6, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=25,}, Push_LanID = 123, Push_Range = 7, },
    [24] = { Push_ID = 24, Push_On = 0, Push_StartTime = 7, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=26,}, Push_LanID = 124, Push_Range = 7, },
    [25] = { Push_ID = 25, Push_On = 0, Push_StartTime = 7, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=27,}, Push_LanID = 125, Push_Range = 7, },
    [26] = { Push_ID = 26, Push_On = 0, Push_StartTime = 8, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=28,}, Push_LanID = 126, Push_Range = 7, },
    [27] = { Push_ID = 27, Push_On = 0, Push_StartTime = 8, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=29,}, Push_LanID = 127, Push_Range = 7, },
    [28] = { Push_ID = 28, Push_On = 0, Push_StartTime = 9, Push_StopTime = -1, Push_Time = 11, Push_Condition = 4, Push_Next = {[1]=16,}, Push_LanID = 128, Push_Range = 7, },
    [29] = { Push_ID = 29, Push_On = 0, Push_StartTime = 9, Push_StopTime = -1, Push_Time = 21, Push_Condition = 4, Push_Next = {[1]=17,}, Push_LanID = 129, Push_Range = 7, },
}
return Cfg_Push