local Cfg_UnlockSetting = {
    [1] = { UnlockSystem = 1, PlayerLevel = 1, },
    [2] = { UnlockSystem = 2, PlayerLevel = 5, },
    [3] = { UnlockSystem = 3, PlayerLevel = 5, },
    [4] = { UnlockSystem = 4, PlayerLevel = 5, },
    [5] = { UnlockSystem = 5, PlayerLevel = 1, },
    [6] = { UnlockSystem = 6, PlayerLevel = 15, },
    [7] = { UnlockSystem = 7, PlayerLevel = 1, },
    [8] = { UnlockSystem = 8, PlayerLevel = 1, },
    [9] = { UnlockSystem = 9, PlayerLevel = 1, },
    [10] = { UnlockSystem = 10, PlayerLevel = 1, },
    [11] = { UnlockSystem = 11, PlayerLevel = 1, },
    [12] = { UnlockSystem = 12, PlayerLevel = 1, },
    [13] = { UnlockSystem = 13, PlayerLevel = 1, },
    [14] = { UnlockSystem = 14, PlayerLevel = 1, },
    [15] = { UnlockSystem = 15, PlayerLevel = 1, },
    [16] = { UnlockSystem = 16, PlayerLevel = 1, },
    [17] = { UnlockSystem = 17, PlayerLevel = 1, },
    [18] = { UnlockSystem = 18, PlayerLevel = 10, },
}
return Cfg_UnlockSetting